/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.





*/
public class Solution {
    public char FindTheDifference(string s, string t) {
        
         int sum = 0;
            foreach(char ch in s)
            {
                sum += (int)ch;
            }

            int sum1 = 0;
            foreach (char ch in t)
            {
                sum1 += (int)ch;
            }
            char character = (char)(sum1 - sum);
            return character;
    }
}
